unit ClientUndServer;

interface
  type
    Pakettyp = (ABBRUCH_DURCH_SERVER, ANMELDUNG, ANMELDUNG_ERFOLGREICH, ANMELDUNG_FEHLGESCHLAGEN, MELDUNG_GEFANGEN, SPIELBEGINN);
    TTeam = (TEAM_ROT, TEAM_BLAU);
    Fehlerart = (ALLGEMEINER_PROTOKOLLFEHLER, FALSCHE_VERSION, TEAM_SCHON_ANGEMELDET, UNGUELTIGE_ROBOTER_ID);

  const
    ANZAHL_ROBOTER = 4;
    PROTOKOLL_VERSION = 1;

implementation

end.
